## MyToDoReact version 1.0.
#
# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: v1
kind: Secret
metadata:
  name: user
data:
  password: ${mtdrdb_user_password}
  walletPassword: ${mtdrdb_walletPassword}
